### ISSUE TITLE
How to use it with plain HTML+CSS+JS

### ISSUE THREAD

**Issue by wooloba** [ysulyma/mathjax-annotations#1]
Hi,
I am wondering how to use it with plain HTML+CSS+JS. If I had a .tex file. Where should I put it and how does annotations.js know the path of .tex?

**Comment by ysulyma** [comment]
Can you explain what you mean by "plain HTML+CSS+JS"? Loading .tex files is beyond the scope of this extension. Here is sample usage:

````JS
// MathJax configuration file
(() => {

MathJax.Ajax.config.path["Extra"] = "/js/vendor/mathjax";

MathJax.Hub.Config({
  TeX: {
    extensions: [
      "[Extra]/annotations.js"
    ]
  }
});

MathJax.Ajax.loadComplete("[Extra]/config.js");

})();
````

```HTML
<!-- HTML file -->

<!-- define macros with annotations -->
<div style="display:none">\[
\newcommand{\R}{\mathbb R}
\Annotate[text]{the real numbers}
\Annotate[defn]{http://your-site.org/lesson1/the-real-number-line}
\]</div>

The real numbers are denoted by \( \R \).
```

**Comment by wooloba** [comment]
I see. 
I am trying to use this extension inside React. I can import the extension properly. Do you have any suggestions on where to store large amounts of macros definition?

**Comment by ysulyma** [comment]
In order to have macro definitions parsed by MathJax, they need to be in a math environment, like above. One option would be to include the contents of the .tex file directly into your HTML on the server side. Another option is to load .tex files via AJAX and then put them into an invisible div which you prepend to document.body prior to calling `MathJax.Hub.Typeset` (this will require `skipStartupTypeset: true` in your MathJax config).

**Comment by wooloba** [comment]
Thank you very much!
I am trying the first option. It is good to know the second option.

**Comment by ysulyma** [comment]
@wooloba see https://github.com/ysulyma/mathjax-load-head for an implementation of the second option as a MathJax extension
